/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Station health at a glance
         * @description Everything the station knows about its own health: capture state (source, mode, tuner centre frequency, dongle presence, the disk-guard pause flag), a three-step trace of the capture chain (database plan → rendered config file → running process) that pinpoints where a frequency change stalled, pipeline queue depths per stage, disk headroom, and today's spend against the external API budgets. `station_name` is null until the owner names the station — the cue for a first-run naming dialog. `timezone` is the IANA zone the dashboard formats local times and calendar days in.
         */
        get: operations["get_status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the frequency plan
         * @description Every frequency the station knows about, active or not, ordered by MHz. Rows with `verified: false` carry placeholder frequencies that have not been checked against a current source and should be displayed with a caveat. Each item links to the action currently available on it (activate or deactivate) and to its recordings.
         */
        get: operations["list_frequencies_frequencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies/{freq_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start recording a frequency
         * @description Adds the frequency to the active plan, rewrites the capture configuration, and restarts capture (a restart drops a few seconds of audio — there is no hot retune). In multichannel mode every active frequency must fit one 2.56 MHz tuner window; when the new set does not fit, the response is a 409 problem detail whose `offenders` lists the frequencies to deactivate and whose `suggested_centerfreq_mhz` is the centre frequency for the largest set that does fit. Switching the station to scan mode is the alternative escape hatch, at the cost of missing concurrent transmissions. Activating an already-active frequency changes nothing. While a deep tune session holds the receiver the plan cannot change: the response is a 409 problem detail with code `deep_tune_active`. While the disk-space guard has capture paused the plan is likewise frozen: the response is a 409 problem detail with code `capture_paused_low_disk`, and the station resumes on its own once free space recovers.
         */
        post: operations["activate_frequency_frequencies__freq_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies/{freq_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop recording a frequency
         * @description Removes the frequency from the active plan, rewrites the capture configuration, and restarts capture. Deactivating the last active frequency stops capture entirely (with a warning in the response) until something is activated again. Deactivating an already-inactive frequency changes nothing. While a deep tune session holds the receiver the plan cannot change: the response is a 409 problem detail with code `deep_tune_active`. While the disk-space guard has capture paused the plan is likewise frozen: the response is a 409 problem detail with code `capture_paused_low_disk`.
         */
        post: operations["deactivate_frequency_frequencies__freq_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the clip library
         * @description Recorded transmissions, newest first, as summary cards: frequency, timing, latest transcript snippet, latest verdict, most plausible aircraft candidate, and feedback tallies. All filters combine. Date filters are inclusive and use the station's local day boundaries. `interesting` and `category` match each clip's latest verdict, so a reclassified clip follows its newest classification. `has_match` selects clips with (or without) aircraft candidates.
         */
        get: operations["list_recordings_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One clip with full provenance
         * @description Everything the station knows about one clip: the latest transcript with engine provenance and confidence, the complete classification history (newest first — verdicts are appended, never overwritten), every ranked aircraft candidate, individual feedback entries, and any pipeline error the clip hit.
         */
        get: operations["get_recording_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a clip's audio
         * @description The clip as MP3 (8 kHz mono as captured). Supports HTTP Range requests, so seeking in an audio player works. Returns 410 once retention has pruned the audio of an old routine clip — the clip's metadata remains available.
         */
        get: operations["get_audio_recordings__recording_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a clip for reclassification
         * @description Sends the clip back through the classifier. The pipeline worker picks it up on its next pass and appends a fresh verdict to the clip's history (nothing is overwritten). Returns 202 immediately; watch the stream or re-fetch the clip for the new verdict. Clips that have not been transcribed yet cannot be reclassified.
         */
        post: operations["reclassify_recording_recordings__recording_id__reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a thumbs-up or thumbs-down
         * @description Stores a listener verdict on whether the clip was worth hearing. Verdicts accumulate — they are individual votes, not a toggle — and feed the all-time greatest-hits list in the digest.
         */
        post: operations["create_feedback_recordings__recording_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clips/interesting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The clips worth hearing
         * @description Clips whose latest verdict is interesting, newest first — the default library view. Equivalent to /recordings?interesting=true, kept as its own route because it is the page most clients open first.
         */
        get: operations["list_interesting_clips_clips_interesting_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One day on the airwaves
         * @description A summary of one station-local day: how many transmissions were recorded, how many were flagged interesting, the interesting clips themselves, and the all-time greatest hits (the clips with the most thumbs-up, regardless of day). Defaults to today; `previous_day` / `next_day` links page through history, and `next_day` is omitted for today. A day with zero recordings returns the same shape with zero counts and empty lists.
         */
        get: operations["get_digest_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The station runbook
         * @description Operating instructions for the station — start/stop, antenna placement, tuning, troubleshooting — as raw Markdown for the client to render.
         */
        get: operations["get_runbook_runbook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The aviation glossary
         * @description Plain-English explanations of the aviation terms that appear in transcripts and classifications, as raw Markdown for the client to render.
         */
        get: operations["get_glossary_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the station settings
         * @description The owner-editable settings. `station_name` is null until the station has been named — the cue to offer a naming dialog on first run.
         */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update station settings
         * @description Partial update: send only the keys to change. Editable keys: `station_name`, and `tuning.walkthrough_done` ('true' or 'false'); anything else is rejected with a 400 problem detail listing the allowed keys. A successful rename is announced on the event stream as `status.changed`, so other open dashboards update live.
         */
        patch: operations["patch_settings_settings_patch"];
        trace?: never;
    };
    "/tuning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the station's tuning state
         * @description The tuning levers as currently applied — tuner gain, the squelch threshold (station default plus any per-frequency overrides), and the frequency correction in ppm — alongside the saved baseline (null until one is saved), the shipped factory values, and the tuner's real gain steps. Gain controls should offer exactly the listed steps: the hardware cannot sit between them. `deep_tune` reports whether an exclusive off-air spectrum session is running, and if so how long it has left before the idle timeout.
         */
        get: operations["get_tuning_tuning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a new set of tuning values
         * @description Persists a complete set of tuning values, rewrites the capture configuration, and restarts capture — the station is off-air for around five seconds. The request is the full value set, not a delta: send the current value for levers that are not changing, and omit a per-frequency override to remove it. Gain is snapped to the tuner's nearest real step. When any value fails validation, nothing is applied and the 422 problem detail names the offender.
         */
        post: operations["post_apply_tuning_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save the applied values as the station baseline
         * @description Snapshots the currently applied tuning values as the station's baseline — the values each lever's reset control returns to. Replaces any previously saved baseline.
         */
        post: operations["post_baseline_tuning_baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the live channel meters
         * @description Per-frequency readings from the capture process's statistics file (rewritten every 15 seconds while capture runs) merged with recording activity: signal and noise in dBFS, the derived signal-to-noise ratio, squelch opens, clips in the last hour, when each frequency last heard a transmission, and clip counts since tuning was last applied. When `stats.present` is false the file has not been written yet — the station may still be starting — and when `stats.stale` is true the numbers are old and meters should show a paused state rather than live values.
         */
        get: operations["get_meters_tuning_meters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/deep-tune/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an exclusive off-air spectrum session
         * @description Stops capture, opens the receiver directly, and streams `spectrum.frame` events over `WS /stream` a few times a second — the station records nothing while the session runs. The server ends the session itself after ten minutes without a ping (a `deep_tune.state` warning event fires one minute beforehand) or within about thirty seconds of every stream client disappearing; every exit path restarts capture.
         */
        post: operations["post_deep_tune_start_tuning_deep_tune_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/deep-tune/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop the deep tune session
         * @description Ends the running spectrum session and restarts capture before responding — the station is back on air when this returns.
         */
        post: operations["post_deep_tune_stop_tuning_deep_tune_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/deep-tune/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keep the deep tune session alive
         * @description Resets the session's idle countdown. Send one whenever the operator interacts with the tuning bench, and periodically while the spectrum view is open.
         */
        post: operations["post_deep_tune_ping_tuning_deep_tune_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIErrorCode
         * @description Stable machine-readable error codes for problem responses.
         * @enum {string}
         */
        APIErrorCode: "validation_error" | "not_found" | "frequency_not_found" | "recording_not_found" | "document_not_found" | "audio_deleted" | "audio_file_missing" | "window_conflict" | "capture_paused_low_disk" | "unknown_setting_key" | "invalid_setting_value" | "tuning_invalid_value" | "tuning_unknown_frequency" | "deep_tune_unavailable" | "deep_tune_active" | "deep_tune_not_active" | "recording_not_classifiable" | "method_not_allowed" | "internal_error";
        /**
         * AircraftMatchResource
         * @description A probable aircraft near the station when the clip was captured.
         *
         *     Candidates are heuristic: they come from position data around the
         *     receiver at capture time, not from decoding the transmission. Present
         *     them as 'probably/possibly', never as fact.
         */
        AircraftMatchResource: {
            /** Id */
            id: number;
            source: components["schemas"]["FlightDataSource"];
            /** Icao24 */
            icao24: string;
            /** Callsign */
            callsign: string | null;
            /** Airline Name */
            airline_name: string | null;
            /**
             * Flight Number Guess
             * @description Marketed flight number inferred from the callsign; a guess by construction, so always phrase it as one.
             */
            flight_number_guess: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt Ft */
            alt_ft: number | null;
            /** Gs Kt */
            gs_kt: number | null;
            /** Distance Km */
            distance_km: number;
            /**
             * Match Confidence
             * @description Ranking confidence in [0, 1].
             */
            match_confidence: number;
            /**
             * Rank
             * @description 1 is the most plausible candidate.
             */
            rank: number;
            /**
             * Queried At
             * Format: date-time
             */
            queried_at: string;
        };
        /**
         * AppliedTuning
         * @description One complete set of tuning values.
         */
        AppliedTuning: {
            /**
             * Gain Db
             * @description RTL-SDR tuner gain; always one of the real gain steps.
             */
            gain_db: number;
            /**
             * Squelch Default Snr Db
             * @description Station-wide squelch threshold: recording starts when a signal rises this many dB above the channel's noise floor.
             */
            squelch_default_snr_db: number;
            /**
             * Ppm
             * @description Frequency correction for the dongle's crystal offset, in parts per million.
             */
            ppm: number;
            /** Squelch Overrides */
            squelch_overrides: components["schemas"]["SquelchOverride"][];
        };
        /**
         * AsrEngine
         * @description Speech-to-text engine that produced a transcript.
         * @enum {string}
         */
        AsrEngine: "faster_whisper" | "whisper_cpp";
        /**
         * BudgetInfo
         * @description Today's consumption against one external API's daily budget.
         */
        BudgetInfo: {
            /** Provider */
            provider: string;
            /** Calls Today */
            calls_today: number;
            /** Daily Cap */
            daily_cap: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * CaptureStatus
         * @description The capture chain as it is right now.
         */
        CaptureStatus: {
            /**
             * Source
             * @description live (real SDR dongle) or replay (fixture playback).
             */
            source: string;
            /**
             * Mode
             * @description multichannel or scan.
             */
            mode: string;
            /** Running */
            running: boolean;
            /** Detail */
            detail: string;
            /**
             * Paused For Disk
             * @description True while the disk-space guard has capture paused.
             */
            paused_for_disk: boolean;
            /**
             * Dongle Present
             * @description Whether an RTL-SDR device is attached; null when not probed (replay).
             */
            dongle_present: boolean | null;
            /**
             * Centerfreq Mhz
             * @description Tuner centre frequency for the active plan; null in scan mode.
             */
            centerfreq_mhz: number | null;
            /**
             * Deep Tune Active
             * @description True while a deep tune session has the receiver: capture is deliberately off-air, not failed.
             * @default false
             */
            deep_tune_active: boolean;
        };
        /**
         * CaptureTrace
         * @description The three-step capture chain: database intent, rendered config file,
         *     running process. Any mismatch between steps points at where a frequency
         *     change stalled.
         */
        CaptureTrace: {
            db_intent: components["schemas"]["TraceIntent"];
            rendered_conf: components["schemas"]["TraceConf"];
            process: components["schemas"]["TraceProcess"];
        };
        /**
         * ChannelMeter
         * @description One frequency's live readings and recent activity.
         */
        ChannelMeter: {
            /** Freq Id */
            freq_id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
            /**
             * Signal Dbfs
             * @description Signal level relative to full scale; null while no stats are available.
             */
            signal_dbfs: number | null;
            /** Noise Dbfs */
            noise_dbfs: number | null;
            /**
             * Snr Db
             * @description Signal above the noise floor — the number squelch compares against.
             */
            snr_db: number | null;
            /**
             * Squelch Level Dbfs
             * @description The level at which squelch currently opens on this channel.
             */
            squelch_level_dbfs: number | null;
            /**
             * Squelch Open Count
             * @description Times squelch has opened since capture started.
             */
            squelch_open_count: number | null;
            /**
             * Flappy Count
             * @description Times squelch opened and closed in quick succession — a high count suggests the threshold sits too close to the noise floor.
             */
            flappy_count: number | null;
            /** Clips Last Hour */
            clips_last_hour: number;
            /** Last Heard Utc */
            last_heard_utc: string | null;
            /**
             * Clips Since Apply
             * @description Clips recorded since tuning was last applied; null if never applied.
             */
            clips_since_apply: number | null;
        };
        /**
         * ClassificationCategory
         * @description Why a clip is (or is not) interesting.
         * @enum {string}
         */
        ClassificationCategory: "routine" | "emergency" | "urgency" | "go_around" | "medical" | "fuel" | "guard_activity" | "unusual" | "other";
        /**
         * ClassificationResource
         * @description One routine/interesting verdict. History is append-only; the newest
         *     verdict is the one that counts.
         */
        ClassificationResource: {
            /** Id */
            id: number;
            /** Is Interesting */
            is_interesting: boolean;
            category: components["schemas"]["ClassificationCategory"];
            /**
             * Confidence
             * @description Verdict confidence in [0, 1].
             */
            confidence: number;
            /**
             * Reason
             * @description Plain-language explanation of the verdict.
             */
            reason: string;
            source: components["schemas"]["ClassificationSource"];
            /**
             * Model
             * @description LLM model name when the source is llm.
             */
            model: string | null;
            /**
             * Prefilter Flags
             * @description Which prefilter rules fired (e.g. keyword:mayday, guard_frequency).
             */
            prefilter_flags: string[];
            /** @description final, or deferred when the daily LLM budget was exhausted and a fuller verdict will be backfilled after the quota resets. */
            status: components["schemas"]["ClassificationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClassificationSource
         * @description Which layer produced a classification verdict.
         * @enum {string}
         */
        ClassificationSource: "prefilter" | "llm";
        /**
         * ClassificationStatus
         * @description Whether a verdict is settled or awaiting an LLM pass after quota reset.
         * @enum {string}
         */
        ClassificationStatus: "final" | "deferred";
        /**
         * ConfState
         * @description How the rtl_airband config file on disk relates to the database plan.
         * @enum {string}
         */
        ConfState: "match" | "stale" | "missing" | "not_applicable";
        /**
         * DeepTuneSessionResponse
         * @description The deep tune session as the start, stop, and ping endpoints report it.
         */
        DeepTuneSessionResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            deep_tune: components["schemas"]["DeepTuneState"];
            /**
             * Center Mhz
             * @description Centre of the spectrum window being streamed; null when inactive.
             */
            center_mhz?: number | null;
            /**
             * Span Mhz
             * @description Full width of the spectrum window in MHz; null when inactive.
             */
            span_mhz?: number | null;
        };
        /**
         * DeepTuneState
         * @description Whether an exclusive off-air spectrum session is running.
         */
        DeepTuneState: {
            /** Active */
            active: boolean;
            /**
             * Started At
             * @description When the session began; null when inactive.
             */
            started_at?: string | null;
            /**
             * Seconds Remaining Before Timeout
             * @description Seconds until the session ends itself for lack of interaction; null when inactive. Pings reset the countdown.
             */
            seconds_remaining_before_timeout?: number | null;
        };
        /**
         * DigestResponse
         * @description One local day on the airwaves, summarised.
         */
        DigestResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Total Count
             * @description Transmissions recorded during the day.
             */
            total_count: number;
            /** Interesting Count */
            interesting_count: number;
            /**
             * Interesting
             * @description The day's interesting clips, newest first.
             */
            interesting: components["schemas"]["RecordingSummary"][];
            /**
             * Greatest Hits
             * @description All-time favourites: the clips with the most thumbs-up.
             */
            greatest_hits: components["schemas"]["RecordingSummary"][];
        };
        /** DiskInfo */
        DiskInfo: {
            /** Free Gb */
            free_gb: number;
            /** Total Gb */
            total_gb: number;
            /**
             * Min Free Gb
             * @description Floor below which capture is paused.
             */
            min_free_gb: number;
            /** Low */
            low: boolean;
        };
        /**
         * DocumentResponse
         * @description A station document as raw Markdown for the client to render.
         */
        DocumentResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Name */
            name: string;
            /** Markdown */
            markdown: string;
        };
        /**
         * FactoryTuning
         * @description The values the station shipped with; the reset of last resort.
         */
        FactoryTuning: {
            /** Gain Db */
            gain_db: number;
            /** Squelch Default Snr Db */
            squelch_default_snr_db: number;
            /** Ppm */
            ppm: number;
        };
        /**
         * FeedbackCounts
         * @description Thumbs-up / thumbs-down tallies for a clip.
         */
        FeedbackCounts: {
            /** Up */
            up: number;
            /** Down */
            down: number;
        };
        /**
         * FeedbackCreate
         * @description Request body for recording a listener verdict.
         */
        FeedbackCreate: {
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Note */
            note?: string | null;
        };
        /**
         * FeedbackResource
         * @description One listener verdict on a clip.
         */
        FeedbackResource: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackVerdict
         * @description Listener thumbs-up / thumbs-down on a clip.
         * @enum {string}
         */
        FeedbackVerdict: "up" | "down";
        /**
         * FlightDataSource
         * @description Where an aircraft match came from.
         * @enum {string}
         */
        FlightDataSource: "opensky";
        /**
         * FrequencyActionResponse
         * @description Result of activating or deactivating a frequency.
         */
        FrequencyActionResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            frequency: components["schemas"]["FrequencyResource"];
            /**
             * Warnings
             * @description Non-fatal notes about the new plan, e.g. the scan-mode concurrency trade-off or a capture restart that could not complete.
             */
            warnings: string[];
            /**
             * Capture Restarted
             * @description Whether the capture process was restarted onto the new plan.
             */
            capture_restarted: boolean;
        };
        /**
         * FrequencyCategory
         * @description What kind of aviation service a frequency carries.
         * @enum {string}
         */
        FrequencyCategory: "guard" | "tower" | "ground" | "approach" | "radar" | "atis" | "area_control" | "airfield";
        /** FrequencyListResponse */
        FrequencyListResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Items */
            items: components["schemas"]["FrequencyResource"][];
        };
        /**
         * FrequencyMode
         * @description Demodulation mode for a monitored frequency.
         * @enum {string}
         */
        FrequencyMode: "am";
        /**
         * FrequencyRef
         * @description Just enough about a frequency to label a clip.
         */
        FrequencyRef: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
        };
        /**
         * FrequencyResource
         * @description One entry in the station's frequency plan.
         */
        FrequencyResource: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
            mode: components["schemas"]["FrequencyMode"];
            /** Facility */
            facility: string;
            category: components["schemas"]["FrequencyCategory"];
            /** Description */
            description: string;
            /**
             * Is Active
             * @description Whether the station currently records this frequency.
             */
            is_active: boolean;
            /** Tuner Group */
            tuner_group: number;
            /**
             * Verified
             * @description False until the frequency has been checked against a current official or enthusiast source; unverified rows deserve a prominent caveat in any UI.
             */
            verified: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Link
         * @description One HAL link: a relative URL on this API.
         */
        Link: {
            /** Href */
            href: string;
        };
        /**
         * MetersResponse
         * @description Live meter readings for every active frequency.
         */
        MetersResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            stats: components["schemas"]["StatsFileState"];
            /** Channels */
            channels: components["schemas"]["ChannelMeter"][];
            since_last_apply: components["schemas"]["SinceLastApply"] | null;
        };
        /**
         * ProblemDetail
         * @description RFC 7807 problem details; the body of every error response.
         */
        ProblemDetail: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            code: components["schemas"]["APIErrorCode"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ReclassifyResponse
         * @description Acknowledgement that a clip was queued for reclassification.
         */
        ReclassifyResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Recording Id */
            recording_id: number;
            stage: components["schemas"]["RecordingStage"];
            /** Detail */
            detail: string;
        };
        /**
         * RecordingDetail
         * @description A clip with its complete provenance.
         */
        RecordingDetail: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            frequency: components["schemas"]["FrequencyRef"];
            /**
             * Started At Utc
             * Format: date-time
             */
            started_at_utc: string;
            /**
             * Ended At Utc
             * Format: date-time
             */
            ended_at_utc: string;
            /** Duration S */
            duration_s: number;
            stage: components["schemas"]["RecordingStage"];
            /**
             * Audio Available
             * @description False once retention has pruned the audio; the row itself is kept.
             */
            audio_available: boolean;
            /**
             * Transcript Snippet
             * @description Opening of the latest transcript, or null while transcription is pending.
             */
            transcript_snippet: string | null;
            /** @description Latest verdict, or null while classification is pending. */
            classification: components["schemas"]["ClassificationResource"] | null;
            /** @description Most plausible aircraft candidate, or null when none was found. */
            top_match: components["schemas"]["AircraftMatchResource"] | null;
            feedback: components["schemas"]["FeedbackCounts"];
            /** Sample Rate */
            sample_rate: number;
            /**
             * File Path
             * @description Audio location relative to the station's data root.
             */
            file_path: string;
            /**
             * Stage Error
             * @description Most recent pipeline failure for this clip, if any stage struggled.
             */
            stage_error: string | null;
            /** Audio Deleted At */
            audio_deleted_at: string | null;
            transcript: components["schemas"]["TranscriptResource"] | null;
            /**
             * Classifications
             * @description Full verdict history, newest first.
             */
            classifications: components["schemas"]["ClassificationResource"][];
            /**
             * Matches
             * @description All candidates, best first.
             */
            matches: components["schemas"]["AircraftMatchResource"][];
            /** Feedback Entries */
            feedback_entries: components["schemas"]["FeedbackResource"][];
        };
        /** RecordingListResponse */
        RecordingListResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Items */
            items: components["schemas"]["RecordingSummary"][];
            /**
             * Total
             * @description Matching clips across all pages.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * RecordingStage
         * @description Lifecycle position of a captured clip in the processing pipeline.
         *
         *     Enrichment failures are recorded but never block transcription or
         *     classification; the failed_* stages mark where a clip needs attention.
         * @enum {string}
         */
        RecordingStage: "captured" | "enriching" | "transcribing" | "transcribed" | "classifying" | "classified" | "failed_enrich" | "failed_transcribe" | "failed_classify";
        /**
         * RecordingSummary
         * @description A clip as it appears in lists and cards.
         */
        RecordingSummary: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            frequency: components["schemas"]["FrequencyRef"];
            /**
             * Started At Utc
             * Format: date-time
             */
            started_at_utc: string;
            /**
             * Ended At Utc
             * Format: date-time
             */
            ended_at_utc: string;
            /** Duration S */
            duration_s: number;
            stage: components["schemas"]["RecordingStage"];
            /**
             * Audio Available
             * @description False once retention has pruned the audio; the row itself is kept.
             */
            audio_available: boolean;
            /**
             * Transcript Snippet
             * @description Opening of the latest transcript, or null while transcription is pending.
             */
            transcript_snippet: string | null;
            /** @description Latest verdict, or null while classification is pending. */
            classification: components["schemas"]["ClassificationResource"] | null;
            /** @description Most plausible aircraft candidate, or null when none was found. */
            top_match: components["schemas"]["AircraftMatchResource"] | null;
            feedback: components["schemas"]["FeedbackCounts"];
        };
        /**
         * SettingsResponse
         * @description The station's owner-editable settings.
         */
        SettingsResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Station Name */
            station_name: string | null;
            /**
             * Tuning Walkthrough Done
             * @description Whether the tuning bench's one-time introductory tour has been completed or dismissed.
             */
            tuning_walkthrough_done: boolean;
        };
        /**
         * SinceLastApply
         * @description Activity since the most recent tuning apply, for before/after comparison.
         */
        SinceLastApply: {
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Total Clips */
            total_clips: number;
        };
        /**
         * SquelchOverride
         * @description A per-frequency squelch threshold that beats the station default.
         */
        SquelchOverride: {
            /** Freq Id */
            freq_id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
            /** Squelch Snr Db */
            squelch_snr_db: number;
        };
        /** SquelchOverrideRequest */
        SquelchOverrideRequest: {
            /** Freq Id */
            freq_id: number;
            /** Squelch Snr Db */
            squelch_snr_db: number;
        };
        /**
         * StatsFileState
         * @description Freshness of the capture process's statistics file.
         */
        StatsFileState: {
            /**
             * Present
             * @description False until capture has written the file at least once.
             */
            present: boolean;
            /**
             * Stale
             * @description True when the file has not been rewritten recently; the numbers describe a process that is no longer reporting, so meters should show a paused state.
             */
            stale: boolean;
            /** Updated At */
            updated_at: string | null;
        };
        /** StatusBudgets */
        StatusBudgets: {
            /** @description Classifier budget; null when classification runs prefilter-only. */
            llm: components["schemas"]["BudgetInfo"] | null;
            /** @description Flight-data credit budget; null when enrichment is disabled. */
            opensky: components["schemas"]["BudgetInfo"] | null;
        };
        /**
         * StatusResponse
         * @description Everything the station knows about its own health.
         */
        StatusResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /**
             * Station Name
             * @description The name the owner gave the station, or null when it has never been named — the signal to offer a first-run naming dialog.
             */
            station_name: string | null;
            /**
             * Timezone
             * @description IANA timezone name the station presents local times in (e.g. `Europe/London`). The dashboard formats every clock and calendar day in this zone rather than assuming one.
             */
            timezone: string;
            capture: components["schemas"]["CaptureStatus"];
            trace: components["schemas"]["CaptureTrace"];
            /**
             * Queues
             * @description Clips per pipeline stage. The failed_* stages are the needs-attention surface.
             */
            queues: {
                [key: string]: number;
            };
            disk: components["schemas"]["DiskInfo"];
            budgets: components["schemas"]["StatusBudgets"];
        };
        /** TraceChannel */
        TraceChannel: {
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
        };
        /**
         * TraceConf
         * @description Whether the rendered config file reflects the database plan.
         */
        TraceConf: {
            state: components["schemas"]["ConfState"];
            /** Path */
            path: string | null;
        };
        /**
         * TraceIntent
         * @description What the database says should be captured.
         */
        TraceIntent: {
            /** Mode */
            mode: string;
            /** Channels */
            channels: components["schemas"]["TraceChannel"][];
        };
        /**
         * TraceProcess
         * @description Whether the capture process is actually running.
         */
        TraceProcess: {
            /** Running */
            running: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * TranscriptResource
         * @description Speech-to-text output with engine provenance.
         */
        TranscriptResource: {
            /** Id */
            id: number;
            engine: components["schemas"]["AsrEngine"];
            /** Model */
            model: string;
            /** Text */
            text: string;
            /**
             * Avg Logprob
             * @description Mean log-probability the recogniser assigned to its own output; closer to 0 is more confident. Values below about -1 deserve a 'rough transcript' caveat. Null when the engine does not report it.
             */
            avg_logprob: number | null;
            /** Language */
            language: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TuningApplyRequest
         * @description A complete set of tuning values — not a delta.
         *
         *     Send the current value for any lever that is not changing; a
         *     per-frequency override omitted here is removed.
         */
        TuningApplyRequest: {
            /** Gain Db */
            gain_db: number;
            /** Squelch Default Snr Db */
            squelch_default_snr_db: number;
            /** Ppm */
            ppm: number;
            /**
             * Squelch Overrides
             * @default []
             */
            squelch_overrides: components["schemas"]["SquelchOverrideRequest"][];
        };
        /**
         * TuningApplyResponse
         * @description The tuning state after an apply, plus how the restart went.
         */
        TuningApplyResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** @description The values capture is currently running with. */
            applied: components["schemas"]["AppliedTuning"];
            /** @description The saved station defaults that per-lever reset returns to, or null when none have been saved yet (factory values apply). */
            baseline: components["schemas"]["AppliedTuning"] | null;
            factory: components["schemas"]["FactoryTuning"];
            /**
             * Gain Steps Db
             * @description The tuner's real gain ladder. Gain controls should offer exactly these values; anything else is snapped to the nearest step.
             */
            gain_steps_db: number[];
            /**
             * Last Applied At
             * @description When tuning values were last applied, or null if never.
             */
            last_applied_at: string | null;
            deep_tune: components["schemas"]["DeepTuneState"];
            /** Capture Restarted */
            capture_restarted: boolean;
            /**
             * Warnings
             * @description Non-fatal notes, e.g. a capture restart that could not complete.
             */
            warnings: string[];
        };
        /**
         * TuningResponse
         * @description The tuning bench's full state.
         */
        TuningResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** @description The values capture is currently running with. */
            applied: components["schemas"]["AppliedTuning"];
            /** @description The saved station defaults that per-lever reset returns to, or null when none have been saved yet (factory values apply). */
            baseline: components["schemas"]["AppliedTuning"] | null;
            factory: components["schemas"]["FactoryTuning"];
            /**
             * Gain Steps Db
             * @description The tuner's real gain ladder. Gain controls should offer exactly these values; anything else is snapped to the nearest step.
             */
            gain_steps_db: number[];
            /**
             * Last Applied At
             * @description When tuning values were last applied, or null if never.
             */
            last_applied_at: string | null;
            deep_tune: components["schemas"]["DeepTuneState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_frequencies_frequencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyListResponse"];
                };
            };
        };
    };
    activate_frequency_frequencies__freq_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                freq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyActionResponse"];
                };
            };
            /** @description Unknown frequency. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The active set would not fit one tuner window, a deep tune session has the receiver, or capture is paused for low disk. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_frequency_frequencies__freq_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                freq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyActionResponse"];
                };
            };
            /** @description Unknown frequency. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A deep tune session has the receiver, or capture is paused for low disk. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_recordings_get: {
        parameters: {
            query?: {
                /** @description Earliest local day to include. */
                from_date?: string | null;
                /** @description Latest local day to include. */
                to_date?: string | null;
                /** @description Only clips from this frequency. */
                freq_id?: number | null;
                /** @description true for clips whose latest verdict is interesting; false for routine. */
                interesting?: boolean | null;
                /** @description Only clips whose latest verdict has this category. */
                category?: components["schemas"]["ClassificationCategory"] | null;
                /** @description Whether clips must have aircraft candidates. */
                has_match?: boolean | null;
                /** @description Clips per page. */
                limit?: number;
                /** @description Clips to skip from the newest. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_recordings__recording_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Partial content for a Range request. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown recording or missing file. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Audio pruned by retention. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclassify_recording_recordings__recording_id__reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReclassifyResponse"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Clip has not been transcribed yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_recordings__recording_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResource"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interesting_clips_clips_interesting_get: {
        parameters: {
            query?: {
                /** @description Clips per page. */
                limit?: number;
                /** @description Clips to skip from the newest. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_digest_get: {
        parameters: {
            query?: {
                /** @description Local day to summarise (YYYY-MM-DD); today when omitted. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runbook_runbook_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Runbook not installed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_glossary_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Glossary not installed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    patch_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Unknown setting key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid setting value. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_tuning_tuning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningResponse"];
                };
            };
        };
    };
    post_apply_tuning_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TuningApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningApplyResponse"];
                };
            };
            /** @description A deep tune session has the receiver (stop it first), or capture is paused for low disk (code `capture_paused_low_disk`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A value is out of range or names an unknown frequency. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    post_baseline_tuning_baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningResponse"];
                };
            };
        };
    };
    get_meters_tuning_meters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetersResponse"];
                };
            };
        };
    };
    post_deep_tune_start_tuning_deep_tune_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepTuneSessionResponse"];
                };
            };
            /** @description A deep tune session is already running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The station cannot stream a spectrum: it is in replay mode, receiver support is not installed, or nothing is active. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    post_deep_tune_stop_tuning_deep_tune_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepTuneSessionResponse"];
                };
            };
            /** @description No deep tune session is running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    post_deep_tune_ping_tuning_deep_tune_ping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepTuneSessionResponse"];
                };
            };
            /** @description No deep tune session is running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
