/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Station health at a glance
         * @description Everything the station knows about its own health: capture state (source, mode, tuner centre frequency, dongle presence, the disk-guard pause flag), a three-step trace of the capture chain (database plan → rendered config file → running process) that pinpoints where a frequency change stalled, pipeline queue depths per stage, disk headroom, and today's spend against the external API budgets. `station_name` is null until the owner names the station — the cue for a first-run naming dialog.
         */
        get: operations["get_status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the frequency plan
         * @description Every frequency the station knows about, active or not, ordered by MHz. Rows with `verified: false` carry placeholder frequencies that have not been checked against a current source and should be displayed with a caveat. Each item links to the action currently available on it (activate or deactivate) and to its recordings.
         */
        get: operations["list_frequencies_frequencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies/{freq_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start recording a frequency
         * @description Adds the frequency to the active plan, rewrites the capture configuration, and restarts capture (a restart drops a few seconds of audio — there is no hot retune). In multichannel mode every active frequency must fit one 2.56 MHz tuner window; when the new set does not fit, the response is a 409 problem detail whose `offenders` lists the frequencies to deactivate and whose `suggested_centerfreq_mhz` is the centre frequency for the largest set that does fit. Switching the station to scan mode is the alternative escape hatch, at the cost of missing concurrent transmissions. Activating an already-active frequency changes nothing.
         */
        post: operations["activate_frequency_frequencies__freq_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frequencies/{freq_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop recording a frequency
         * @description Removes the frequency from the active plan, rewrites the capture configuration, and restarts capture. Deactivating the last active frequency stops capture entirely (with a warning in the response) until something is activated again. Deactivating an already-inactive frequency changes nothing.
         */
        post: operations["deactivate_frequency_frequencies__freq_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the clip library
         * @description Recorded transmissions, newest first, as summary cards: frequency, timing, latest transcript snippet, latest verdict, most plausible aircraft candidate, and feedback tallies. All filters combine. Date filters are inclusive and use the station's local day boundaries. `interesting` and `category` match each clip's latest verdict, so a reclassified clip follows its newest classification. `has_match` selects clips with (or without) aircraft candidates.
         */
        get: operations["list_recordings_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One clip with full provenance
         * @description Everything the station knows about one clip: the latest transcript with engine provenance and confidence, the complete classification history (newest first — verdicts are appended, never overwritten), every ranked aircraft candidate, individual feedback entries, and any pipeline error the clip hit.
         */
        get: operations["get_recording_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a clip's audio
         * @description The clip as MP3 (8 kHz mono as captured). Supports HTTP Range requests, so seeking in an audio player works. Returns 410 once retention has pruned the audio of an old routine clip — the clip's metadata remains available.
         */
        get: operations["get_audio_recordings__recording_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a clip for reclassification
         * @description Sends the clip back through the classifier. The pipeline worker picks it up on its next pass and appends a fresh verdict to the clip's history (nothing is overwritten). Returns 202 immediately; watch the stream or re-fetch the clip for the new verdict. Clips that have not been transcribed yet cannot be reclassified.
         */
        post: operations["reclassify_recording_recordings__recording_id__reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a thumbs-up or thumbs-down
         * @description Stores a listener verdict on whether the clip was worth hearing. Verdicts accumulate — they are individual votes, not a toggle — and feed the all-time greatest-hits list in the digest.
         */
        post: operations["create_feedback_recordings__recording_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clips/interesting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The clips worth hearing
         * @description Clips whose latest verdict is interesting, newest first — the default library view. Equivalent to /recordings?interesting=true, kept as its own route because it is the page most clients open first.
         */
        get: operations["list_interesting_clips_clips_interesting_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One day on the airwaves
         * @description A summary of one station-local day: how many transmissions were recorded, how many were flagged interesting, the interesting clips themselves, and the all-time greatest hits (the clips with the most thumbs-up, regardless of day). Defaults to today; `previous_day` / `next_day` links page through history, and `next_day` is omitted for today. A day with zero recordings returns the same shape with zero counts and empty lists.
         */
        get: operations["get_digest_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The station runbook
         * @description Operating instructions for the station — start/stop, antenna placement, tuning, troubleshooting — as raw Markdown for the client to render.
         */
        get: operations["get_runbook_runbook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The aviation glossary
         * @description Plain-English explanations of the aviation terms that appear in transcripts and classifications, as raw Markdown for the client to render.
         */
        get: operations["get_glossary_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the station settings
         * @description The owner-editable settings. `station_name` is null until the station has been named — the cue to offer a naming dialog on first run.
         */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update station settings
         * @description Partial update: send only the keys to change. `station_name` is currently the only editable key; anything else is rejected with a 400 problem detail listing the allowed keys. A successful rename is announced on the event stream as `status.changed`, so other open dashboards update live.
         */
        patch: operations["patch_settings_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIErrorCode
         * @description Stable machine-readable error codes for problem responses.
         * @enum {string}
         */
        APIErrorCode: "validation_error" | "not_found" | "frequency_not_found" | "recording_not_found" | "document_not_found" | "audio_deleted" | "audio_file_missing" | "window_conflict" | "unknown_setting_key" | "invalid_setting_value" | "recording_not_classifiable" | "method_not_allowed" | "internal_error";
        /**
         * AircraftMatchResource
         * @description A probable aircraft near the station when the clip was captured.
         *
         *     Candidates are heuristic: they come from position data around the
         *     receiver at capture time, not from decoding the transmission. Present
         *     them as 'probably/possibly', never as fact.
         */
        AircraftMatchResource: {
            /** Id */
            id: number;
            source: components["schemas"]["FlightDataSource"];
            /** Icao24 */
            icao24: string;
            /** Callsign */
            callsign: string | null;
            /** Airline Name */
            airline_name: string | null;
            /**
             * Flight Number Guess
             * @description Marketed flight number inferred from the callsign; a guess by construction, so always phrase it as one.
             */
            flight_number_guess: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt Ft */
            alt_ft: number | null;
            /** Gs Kt */
            gs_kt: number | null;
            /** Distance Km */
            distance_km: number;
            /**
             * Match Confidence
             * @description Ranking confidence in [0, 1].
             */
            match_confidence: number;
            /**
             * Rank
             * @description 1 is the most plausible candidate.
             */
            rank: number;
            /**
             * Queried At
             * Format: date-time
             */
            queried_at: string;
        };
        /**
         * AsrEngine
         * @description Speech-to-text engine that produced a transcript.
         * @enum {string}
         */
        AsrEngine: "faster_whisper" | "whisper_cpp";
        /**
         * BudgetInfo
         * @description Today's consumption against one external API's daily budget.
         */
        BudgetInfo: {
            /** Provider */
            provider: string;
            /** Calls Today */
            calls_today: number;
            /** Daily Cap */
            daily_cap: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * CaptureStatus
         * @description The capture chain as it is right now.
         */
        CaptureStatus: {
            /**
             * Source
             * @description live (real SDR dongle) or replay (fixture playback).
             */
            source: string;
            /**
             * Mode
             * @description multichannel or scan.
             */
            mode: string;
            /** Running */
            running: boolean;
            /** Detail */
            detail: string;
            /**
             * Paused For Disk
             * @description True while the disk-space guard has capture paused.
             */
            paused_for_disk: boolean;
            /**
             * Dongle Present
             * @description Whether an RTL-SDR device is attached; null when not probed (replay).
             */
            dongle_present: boolean | null;
            /**
             * Centerfreq Mhz
             * @description Tuner centre frequency for the active plan; null in scan mode.
             */
            centerfreq_mhz: number | null;
        };
        /**
         * CaptureTrace
         * @description The three-step capture chain: database intent, rendered config file,
         *     running process. Any mismatch between steps points at where a frequency
         *     change stalled.
         */
        CaptureTrace: {
            db_intent: components["schemas"]["TraceIntent"];
            rendered_conf: components["schemas"]["TraceConf"];
            process: components["schemas"]["TraceProcess"];
        };
        /**
         * ClassificationCategory
         * @description Why a clip is (or is not) interesting.
         * @enum {string}
         */
        ClassificationCategory: "routine" | "emergency" | "urgency" | "go_around" | "medical" | "fuel" | "guard_activity" | "unusual" | "other";
        /**
         * ClassificationResource
         * @description One routine/interesting verdict. History is append-only; the newest
         *     verdict is the one that counts.
         */
        ClassificationResource: {
            /** Id */
            id: number;
            /** Is Interesting */
            is_interesting: boolean;
            category: components["schemas"]["ClassificationCategory"];
            /**
             * Confidence
             * @description Verdict confidence in [0, 1].
             */
            confidence: number;
            /**
             * Reason
             * @description Plain-language explanation of the verdict.
             */
            reason: string;
            source: components["schemas"]["ClassificationSource"];
            /**
             * Model
             * @description LLM model name when the source is llm.
             */
            model: string | null;
            /**
             * Prefilter Flags
             * @description Which prefilter rules fired (e.g. keyword:mayday, guard_frequency).
             */
            prefilter_flags: string[];
            /** @description final, or deferred when the daily LLM budget was exhausted and a fuller verdict will be backfilled after the quota resets. */
            status: components["schemas"]["ClassificationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClassificationSource
         * @description Which layer produced a classification verdict.
         * @enum {string}
         */
        ClassificationSource: "prefilter" | "llm";
        /**
         * ClassificationStatus
         * @description Whether a verdict is settled or awaiting an LLM pass after quota reset.
         * @enum {string}
         */
        ClassificationStatus: "final" | "deferred";
        /**
         * ConfState
         * @description How the rtl_airband config file on disk relates to the database plan.
         * @enum {string}
         */
        ConfState: "match" | "stale" | "missing" | "not_applicable";
        /**
         * DigestResponse
         * @description One local day on the airwaves, summarised.
         */
        DigestResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Total Count
             * @description Transmissions recorded during the day.
             */
            total_count: number;
            /** Interesting Count */
            interesting_count: number;
            /**
             * Interesting
             * @description The day's interesting clips, newest first.
             */
            interesting: components["schemas"]["RecordingSummary"][];
            /**
             * Greatest Hits
             * @description All-time favourites: the clips with the most thumbs-up.
             */
            greatest_hits: components["schemas"]["RecordingSummary"][];
        };
        /** DiskInfo */
        DiskInfo: {
            /** Free Gb */
            free_gb: number;
            /** Total Gb */
            total_gb: number;
            /**
             * Min Free Gb
             * @description Floor below which capture is paused.
             */
            min_free_gb: number;
            /** Low */
            low: boolean;
        };
        /**
         * DocumentResponse
         * @description A station document as raw Markdown for the client to render.
         */
        DocumentResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Name */
            name: string;
            /** Markdown */
            markdown: string;
        };
        /**
         * FeedbackCounts
         * @description Thumbs-up / thumbs-down tallies for a clip.
         */
        FeedbackCounts: {
            /** Up */
            up: number;
            /** Down */
            down: number;
        };
        /**
         * FeedbackCreate
         * @description Request body for recording a listener verdict.
         */
        FeedbackCreate: {
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Note */
            note?: string | null;
        };
        /**
         * FeedbackResource
         * @description One listener verdict on a clip.
         */
        FeedbackResource: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            verdict: components["schemas"]["FeedbackVerdict"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackVerdict
         * @description Listener thumbs-up / thumbs-down on a clip.
         * @enum {string}
         */
        FeedbackVerdict: "up" | "down";
        /**
         * FlightDataSource
         * @description Where an aircraft match came from.
         * @enum {string}
         */
        FlightDataSource: "opensky";
        /**
         * FrequencyActionResponse
         * @description Result of activating or deactivating a frequency.
         */
        FrequencyActionResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            frequency: components["schemas"]["FrequencyResource"];
            /**
             * Warnings
             * @description Non-fatal notes about the new plan, e.g. the scan-mode concurrency trade-off or a capture restart that could not complete.
             */
            warnings: string[];
            /**
             * Capture Restarted
             * @description Whether the capture process was restarted onto the new plan.
             */
            capture_restarted: boolean;
        };
        /**
         * FrequencyCategory
         * @description What kind of aviation service a frequency carries.
         * @enum {string}
         */
        FrequencyCategory: "guard" | "tower" | "ground" | "approach" | "radar" | "atis" | "area_control" | "airfield";
        /** FrequencyListResponse */
        FrequencyListResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Items */
            items: components["schemas"]["FrequencyResource"][];
        };
        /**
         * FrequencyMode
         * @description Demodulation mode for a monitored frequency.
         * @enum {string}
         */
        FrequencyMode: "am";
        /**
         * FrequencyRef
         * @description Just enough about a frequency to label a clip.
         */
        FrequencyRef: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
        };
        /**
         * FrequencyResource
         * @description One entry in the station's frequency plan.
         */
        FrequencyResource: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
            mode: components["schemas"]["FrequencyMode"];
            /** Facility */
            facility: string;
            category: components["schemas"]["FrequencyCategory"];
            /** Description */
            description: string;
            /**
             * Is Active
             * @description Whether the station currently records this frequency.
             */
            is_active: boolean;
            /** Tuner Group */
            tuner_group: number;
            /**
             * Verified
             * @description False until the frequency has been checked against a current official or enthusiast source; unverified rows deserve a prominent caveat in any UI.
             */
            verified: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Link
         * @description One HAL link: a relative URL on this API.
         */
        Link: {
            /** Href */
            href: string;
        };
        /**
         * ProblemDetail
         * @description RFC 7807 problem details; the body of every error response.
         */
        ProblemDetail: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            code: components["schemas"]["APIErrorCode"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ReclassifyResponse
         * @description Acknowledgement that a clip was queued for reclassification.
         */
        ReclassifyResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Recording Id */
            recording_id: number;
            stage: components["schemas"]["RecordingStage"];
            /** Detail */
            detail: string;
        };
        /**
         * RecordingDetail
         * @description A clip with its complete provenance.
         */
        RecordingDetail: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            frequency: components["schemas"]["FrequencyRef"];
            /**
             * Started At Utc
             * Format: date-time
             */
            started_at_utc: string;
            /**
             * Ended At Utc
             * Format: date-time
             */
            ended_at_utc: string;
            /** Duration S */
            duration_s: number;
            stage: components["schemas"]["RecordingStage"];
            /**
             * Audio Available
             * @description False once retention has pruned the audio; the row itself is kept.
             */
            audio_available: boolean;
            /**
             * Transcript Snippet
             * @description Opening of the latest transcript, or null while transcription is pending.
             */
            transcript_snippet: string | null;
            /** @description Latest verdict, or null while classification is pending. */
            classification: components["schemas"]["ClassificationResource"] | null;
            /** @description Most plausible aircraft candidate, or null when none was found. */
            top_match: components["schemas"]["AircraftMatchResource"] | null;
            feedback: components["schemas"]["FeedbackCounts"];
            /** Sample Rate */
            sample_rate: number;
            /**
             * File Path
             * @description Audio location relative to the station's data root.
             */
            file_path: string;
            /**
             * Stage Error
             * @description Most recent pipeline failure for this clip, if any stage struggled.
             */
            stage_error: string | null;
            /** Audio Deleted At */
            audio_deleted_at: string | null;
            transcript: components["schemas"]["TranscriptResource"] | null;
            /**
             * Classifications
             * @description Full verdict history, newest first.
             */
            classifications: components["schemas"]["ClassificationResource"][];
            /**
             * Matches
             * @description All candidates, best first.
             */
            matches: components["schemas"]["AircraftMatchResource"][];
            /** Feedback Entries */
            feedback_entries: components["schemas"]["FeedbackResource"][];
        };
        /** RecordingListResponse */
        RecordingListResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Items */
            items: components["schemas"]["RecordingSummary"][];
            /**
             * Total
             * @description Matching clips across all pages.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * RecordingStage
         * @description Lifecycle position of a captured clip in the processing pipeline.
         *
         *     Enrichment failures are recorded but never block transcription or
         *     classification; the failed_* stages mark where a clip needs attention.
         * @enum {string}
         */
        RecordingStage: "captured" | "enriching" | "transcribing" | "transcribed" | "classifying" | "classified" | "failed_enrich" | "failed_transcribe" | "failed_classify";
        /**
         * RecordingSummary
         * @description A clip as it appears in lists and cards.
         */
        RecordingSummary: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Id */
            id: number;
            frequency: components["schemas"]["FrequencyRef"];
            /**
             * Started At Utc
             * Format: date-time
             */
            started_at_utc: string;
            /**
             * Ended At Utc
             * Format: date-time
             */
            ended_at_utc: string;
            /** Duration S */
            duration_s: number;
            stage: components["schemas"]["RecordingStage"];
            /**
             * Audio Available
             * @description False once retention has pruned the audio; the row itself is kept.
             */
            audio_available: boolean;
            /**
             * Transcript Snippet
             * @description Opening of the latest transcript, or null while transcription is pending.
             */
            transcript_snippet: string | null;
            /** @description Latest verdict, or null while classification is pending. */
            classification: components["schemas"]["ClassificationResource"] | null;
            /** @description Most plausible aircraft candidate, or null when none was found. */
            top_match: components["schemas"]["AircraftMatchResource"] | null;
            feedback: components["schemas"]["FeedbackCounts"];
        };
        /**
         * SettingsResponse
         * @description The station's owner-editable settings.
         */
        SettingsResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Station Name */
            station_name: string | null;
        };
        /** StatusBudgets */
        StatusBudgets: {
            /** @description Classifier budget; null when classification runs prefilter-only. */
            llm: components["schemas"]["BudgetInfo"] | null;
            /** @description Flight-data credit budget; null when enrichment is disabled. */
            opensky: components["schemas"]["BudgetInfo"] | null;
        };
        /**
         * StatusResponse
         * @description Everything the station knows about its own health.
         */
        StatusResponse: {
            /**
             * Links
             * @description HAL links: self plus related resources and the actions currently available on this resource.
             */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /**
             * Station Name
             * @description The name the owner gave the station, or null when it has never been named — the signal to offer a first-run naming dialog.
             */
            station_name: string | null;
            capture: components["schemas"]["CaptureStatus"];
            trace: components["schemas"]["CaptureTrace"];
            /**
             * Queues
             * @description Clips per pipeline stage. The failed_* stages are the needs-attention surface.
             */
            queues: {
                [key: string]: number;
            };
            disk: components["schemas"]["DiskInfo"];
            budgets: components["schemas"]["StatusBudgets"];
        };
        /** TraceChannel */
        TraceChannel: {
            /** Label */
            label: string;
            /** Mhz */
            mhz: number;
        };
        /**
         * TraceConf
         * @description Whether the rendered config file reflects the database plan.
         */
        TraceConf: {
            state: components["schemas"]["ConfState"];
            /** Path */
            path: string | null;
        };
        /**
         * TraceIntent
         * @description What the database says should be captured.
         */
        TraceIntent: {
            /** Mode */
            mode: string;
            /** Channels */
            channels: components["schemas"]["TraceChannel"][];
        };
        /**
         * TraceProcess
         * @description Whether the capture process is actually running.
         */
        TraceProcess: {
            /** Running */
            running: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * TranscriptResource
         * @description Speech-to-text output with engine provenance.
         */
        TranscriptResource: {
            /** Id */
            id: number;
            engine: components["schemas"]["AsrEngine"];
            /** Model */
            model: string;
            /** Text */
            text: string;
            /**
             * Avg Logprob
             * @description Mean log-probability the recogniser assigned to its own output; closer to 0 is more confident. Values below about -1 deserve a 'rough transcript' caveat. Null when the engine does not report it.
             */
            avg_logprob: number | null;
            /** Language */
            language: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_frequencies_frequencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyListResponse"];
                };
            };
        };
    };
    activate_frequency_frequencies__freq_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                freq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyActionResponse"];
                };
            };
            /** @description Unknown frequency. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The active set would not fit one tuner window. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_frequency_frequencies__freq_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                freq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyActionResponse"];
                };
            };
            /** @description Unknown frequency. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_recordings_get: {
        parameters: {
            query?: {
                /** @description Earliest local day to include. */
                from_date?: string | null;
                /** @description Latest local day to include. */
                to_date?: string | null;
                /** @description Only clips from this frequency. */
                freq_id?: number | null;
                /** @description true for clips whose latest verdict is interesting; false for routine. */
                interesting?: boolean | null;
                /** @description Only clips whose latest verdict has this category. */
                category?: components["schemas"]["ClassificationCategory"] | null;
                /** @description Whether clips must have aircraft candidates. */
                has_match?: boolean | null;
                /** @description Clips per page. */
                limit?: number;
                /** @description Clips to skip from the newest. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_recordings__recording_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Partial content for a Range request. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown recording or missing file. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Audio pruned by retention. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclassify_recording_recordings__recording_id__reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReclassifyResponse"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Clip has not been transcribed yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_recordings__recording_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResource"];
                };
            };
            /** @description Unknown recording. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interesting_clips_clips_interesting_get: {
        parameters: {
            query?: {
                /** @description Clips per page. */
                limit?: number;
                /** @description Clips to skip from the newest. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_digest_get: {
        parameters: {
            query?: {
                /** @description Local day to summarise (YYYY-MM-DD); today when omitted. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runbook_runbook_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Runbook not installed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_glossary_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Glossary not installed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    patch_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Unknown setting key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid setting value. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
