"""initial schema

Revision ID: 4f41a40b5f5d
Revises:
Create Date: 2026-07-16 18:18:09.817654

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f41a40b5f5d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("gemini", "groq", "ollama", "opensky", name="apiprovider", native_enum=False),
            nullable=False,
        ),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "day", name="uq_api_usage_provider_day"),
    )
    op.create_table(
        "frequencies",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mhz", sa.Float(), nullable=False),
        sa.Column("mode", sa.Enum("am", name="frequencymode", native_enum=False), nullable=False),
        sa.Column("facility", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "guard",
                "tower",
                "ground",
                "approach",
                "radar",
                "atis",
                "area_control",
                "airfield",
                name="frequencycategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tuner_group", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label", "mhz", name="uq_frequencies_label_mhz"),
    )
    with op.batch_alter_table("frequencies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_frequencies_label"), ["label"], unique=False)

    op.create_table(
        "settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "recordings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("freq_id", sa.Integer(), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(), nullable=False),
        sa.Column("ended_at_utc", sa.DateTime(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "captured",
                "enriching",
                "transcribing",
                "transcribed",
                "classifying",
                "classified",
                "failed_enrich",
                "failed_transcribe",
                "failed_classify",
                name="recordingstage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stage_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["freq_id"],
            ["frequencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recordings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recordings_freq_id"), ["freq_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recordings_stage"), ["stage"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recordings_started_at_utc"), ["started_at_utc"], unique=False
        )

    op.create_table(
        "aircraft_matches",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sa.Enum("opensky", name="flightdatasource", native_enum=False), nullable=False
        ),
        sa.Column("icao24", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("callsign", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("airline_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("flight_number_guess", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("alt_ft", sa.Float(), nullable=True),
        sa.Column("gs_kt", sa.Float(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("queried_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("aircraft_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_aircraft_matches_recording_id"), ["recording_id"], unique=False
        )

    op.create_table(
        "classifications",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("is_interesting", sa.Boolean(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "routine",
                "emergency",
                "urgency",
                "go_around",
                "medical",
                "fuel",
                "guard_activity",
                "unusual",
                "other",
                name="classificationcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("prefilter", "llm", name="classificationsource", native_enum=False),
            nullable=False,
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prefilter_flags", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("final", "deferred", name="classificationstatus", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_classifications_recording_id"), ["recording_id"], unique=False
        )

    op.create_table(
        "feedback",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("up", "down", name="feedbackverdict", native_enum=False),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_recording_id"), ["recording_id"], unique=False
        )

    op.create_table(
        "transcripts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column(
            "engine",
            sa.Enum("faster_whisper", "whisper_cpp", name="asrengine", native_enum=False),
            nullable=False,
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avg_logprob", sa.Float(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transcripts_recording_id"), ["recording_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcripts_recording_id"))

    op.drop_table("transcripts")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_recording_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classifications_recording_id"))

    op.drop_table("classifications")
    with op.batch_alter_table("aircraft_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aircraft_matches_recording_id"))

    op.drop_table("aircraft_matches")
    with op.batch_alter_table("recordings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recordings_started_at_utc"))
        batch_op.drop_index(batch_op.f("ix_recordings_stage"))
        batch_op.drop_index(batch_op.f("ix_recordings_freq_id"))

    op.drop_table("recordings")
    op.drop_table("settings")
    with op.batch_alter_table("frequencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_frequencies_label"))

    op.drop_table("frequencies")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
