"""Renders the rtl_airband configuration from the frequency plan.

The conf file is a generated artifact: the ``frequencies`` table plus the
station's capture settings are the source of truth, and the output is
deterministic so that regenerating with unchanged inputs is a no-op.

Output choices baked in here (and relied on by the watcher):

- MP3 file outputs only — rtl_airband's file output is MP3-only for AM.
- ``split_on_transmission`` + ``include_freq`` so each transmission becomes
  one file whose name carries the UTC start time and frequency in Hz.
- ``dated_subdirectories`` so clips nest under ``YYYY/MM/DD``.
"""

from collections.abc import Sequence
from pathlib import Path

from skywatch.capture.filenames import slugify_label
from skywatch.capture.validate import validate_frequencies
from skywatch.db.models import Frequency
from skywatch.settings import CaptureSettings

HEADER = (
    "# Generated by skywatch from the frequency plan and station settings.\n"
    "# Do not edit: this file is rewritten every time capture (re)starts.\n"
)

SCAN_FILENAME_TEMPLATE = "scan"


def _num(value: float) -> str:
    """libconfig is typed: always render numerics as floats (e.g. ``32.0``)."""
    text = f"{value:.10g}"
    return text if "." in text or "e" in text else f"{text}.0"


def _output_block(directory: Path, filename_template: str, indent: str) -> list[str]:
    return [
        f"{indent}outputs:",
        f"{indent}(",
        f"{indent}  {{",
        f'{indent}    type = "file";',
        f'{indent}    directory = "{directory.as_posix()}";',
        f'{indent}    filename_template = "{filename_template}";',
        f"{indent}    split_on_transmission = true;",
        f"{indent}    include_freq = true;",
        f"{indent}    dated_subdirectories = true;",
        f"{indent}  }}",
        f"{indent});",
    ]


def render_conf(
    frequencies: Sequence[Frequency],
    capture: CaptureSettings,
    *,
    recordings_dir: Path,
) -> str:
    """Render the full rtl_airband.conf for the active frequency set.

    Raises ``ValueError`` when the set is invalid for the configured mode —
    callers should have validated already; this is the last line of defence
    against writing a conf rtl_airband would reject or mis-capture.
    """
    result = validate_frequencies(frequencies, capture.mode)
    if not result.ok:
        raise ValueError("; ".join(result.errors))

    ordered = sorted(frequencies, key=lambda f: f.mhz)
    lines = [HEADER, "devices:", "(", "  {", '    type = "rtlsdr";']
    lines.append(f"    index = {capture.device_index};")
    lines.append(f"    gain = {_num(capture.gain)};")
    lines.append(f'    mode = "{capture.mode}";')
    if capture.mode == "multichannel":
        assert result.suggested_centerfreq_mhz is not None
        lines.append(f"    centerfreq = {_num(result.suggested_centerfreq_mhz)};")
    lines.append(f"    sample_rate = {_num(capture.sample_rate_msps)};")
    lines.append("    channels:")
    lines.append("    (")

    if capture.mode == "multichannel":
        blocks = []
        for channel in ordered:
            block = [
                "      {",
                f"        freq = {_num(channel.mhz)};",
                f'        modulation = "{channel.mode.value}";',
                f"        squelch_snr_threshold = {_num(capture.squelch_snr_threshold)};",
                *_output_block(recordings_dir, slugify_label(channel.label), "        "),
                "      }",
            ]
            blocks.append("\n".join(block))
        lines.append(",\n".join(blocks))
    else:
        freq_list = ", ".join(_num(channel.mhz) for channel in ordered)
        block = [
            "      {",
            f"        freqs = ( {freq_list} );",
            f'        modulation = "{ordered[0].mode.value}";',
            f"        squelch_snr_threshold = {_num(capture.squelch_snr_threshold)};",
            *_output_block(recordings_dir, SCAN_FILENAME_TEMPLATE, "        "),
            "      }",
        ]
        lines.append("\n".join(block))

    lines.extend(["    );", "  }", ");", ""])
    return "\n".join(lines)
